# Generated by Django 5.1.6 on 2025-02-22 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='description_file',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='description_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customizedresume',
            name='job_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jobdescription'),
        ),
    ]
