
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_db
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"